# Generated by Django 2.2 on 2019-04-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=12)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=12)),
                ('estadogeo', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
